In [45]:
import numpy as np

In [51]:
cities_name = np.genfromtxt('world_cities_full_info.csv',dtype='str',delimiter=',',usecols=(0))
cities_lat, cities_lng, cities_alt= np.genfromtxt('world_cities_full_info.csv',dtype='float',delimiter=',',usecols=(1,2,3),unpack = True)

In [52]:
cities_name

array(['Kabul', 'Kandahar', 'Mazar-e Sharif', ..., 'Kamativi',
       'Lalapansi', 'Madziwa'], dtype='<U39')

In [53]:
cities_lat

array([ 34.5166667,  31.61     ,  36.7069444, ..., -18.3166667,
       -19.3333333, -16.9166667])

In [54]:
cities_lng

array([69.1833344, 65.6999969, 67.1122208, ..., 27.0666676, 30.1833324,
       31.5333328])

In [55]:
cities_alt

array([1808., 1015.,  369., ...,  941., 1493., 1108.])